Mon group1/session11/refactor structure
suyttthideptrai/SS1_2023_StableMatchingSolver_Backend pull request #16
Opened 2024-11-03 14:49 UTC by SilverSixx

2024-11-04 15:28 UTC, suyttthideptrai commented on structure.md
> +    │       │   ├── Matcher.java           # Interface or abstract class for matching algorithms, manage the actual matching process, including handling preferences and matches.
Nghiên cứu về việc dùng chung một class Matches, không chia nhỏ các case, có thể xem xét sử dụng Map thay vì Vector nếu performance tốt hơn -> Ảnh hưởng: FE có thể sẽ phải sửa cách dịch kết quả từ BE do Map có thể sẽ không đảm bảo thứ tự.

2024-11-04 15:37 UTC, suyttthideptrai commented on structure.md
> +    │           ├── Evaluator.java          # Interface for the evaluator
Evaluator sẽ evaluate đầu ra cho cả GT và SMP hử?
-> Có nên như vậy không hay tách ra?
-> Nếu dùng chung thì sẽ thống nhất là dùng chung Exp4j để evaluate các thứ lquan đến hàm số? -> ảnh hưởng: sửa cả phần của GT -> có nên ko? Chắc là ko nên do code bên GT cũng khá ổn định r.

2024-11-04 15:38 UTC, suyttthideptrai commented on structure.md
> +    │       │   ├── Preference.java            # Preference entity
Chưa hiểu về phần Preference và PreferenceProvider lắm, có thể giải thích thêm cho TA được không? NewPreferenceProvider dự định sẽ cải tiến những gì so với Old?

2024-11-04 15:59 UTC, SilverSixx commented on src/main/java/com/example/SS2_Backend/model/stableMatching/StableMatchingOTMProblem.java
1. ok toi se check 
2. confirm, nếu solution có pair bị exclude, thì sẽ bỏ luôn solution.

2024-11-04 16:00 UTC, SilverSixx commented on structure.md
> +    │           ├── Evaluator.java          # Interface for the evaluator
evaluator chỉ dành cho matching, k liên quan tới gt

2024-11-04 16:01 UTC, SilverSixx commented on structure.md
> +    │       │   ├── Preference.java            # Preference entity
=)), hiện tại đang có 2 cái pref provider, nên tôi mới để là old và new, old là case của ông, còn new là của duy
ok sẽ xem lại cái class preference

2024-11-04 16:02 UTC, SilverSixx commented on structure.md
> +    ├── exception/                        # Custom exceptions for error handling
cái này bro comment tôi chưa hiểu

2024-11-04 16:02 UTC, SilverSixx commented on structure.md
> +    │   ├── StableMatchingService.java    # Interface for stable matching service
là sao bro ?

2024-11-04 16:03 UTC, suyttthideptrai commented on structure.md
> +    │       │   ├── Preference.java            # Preference entity
kê

2024-11-04 16:04 UTC, suyttthideptrai commented on structure.md
> +    │           ├── Evaluator.java          # Interface for the evaluator
kê

2024-11-04 16:07 UTC, suyttthideptrai commented on structure.md
> +    ├── exception/                        # Custom exceptions for error handling
Tức là mình có thể define một Exception gốc với các hàm get error có thể extend đc. Khi thg controller bắt được Exception mình define thì có thể build được response với format chuẩn luôn.

2024-11-04 16:08 UTC, suyttthideptrai commented on src/main/java/com/example/SS2_Backend/model/stableMatching/StableMatchingOTMProblem.java
kê

2024-11-04 16:11 UTC, SilverSixx commented on structure.md
> +    ├── exception/                        # Custom exceptions for error handling
um, gần hiểu =))

2024-11-07 05:28 UTC, han8129 requested changes
Miêu tả cho kiến trúc chưa rõ ràng - không thể hiện được mối liên hệ giữa các module. MVC dùng cho hệ thống này là không thích hợp

2024-11-07 05:28 UTC, han8129 commented on structure.md
# Chưa miêu tả được liên hệ giữa các package

# Không có Architecture rõ ràng
Bản thân MVC không phù hợp với hệ thống, pattern này dùng để người dùng tương tác với data thì được, nhưng hệ thống này chỉ cho input rồi đợi output.

Nên dùng Pipe-Filter Architecture, rồi với module stable matching thì sử dụng Strategy pattern

## View đã được tách riêng
Dù không có view nhưng document vẫn nhắc đến và giải thích - tôi đoán là dùng AI viết, dù dùng cái gì thì cũng cần review

## Model chứa các Class không liên quan đến data
Bản thân các problem không hề có trách nghiệm chứa data, problem chỉ thực hiện việc chạy thuật toán theo thứ tự. Nên có một package riêng như là `libs`

## MatchingSolution là một DTO

# Class thừa
Preference - bản thân nó chỉ là một float number thôi không cần có một class riêng
IndiviualList - không có quá nhiều giá trị, xem xét bỏ và dùng List<Individual>

2024-11-07 13:46 UTC, merged