Xử lý DTO Validation (Pull Request cuối cho Branch)
suyttthideptrai/SS1_2023_StableMatchingSolver_Backend pull request #17
Opened 2024-11-07 13:37 UTC by duy103zxc

Đây là phần làm của em cho nhiệm vụ xử lý DTO Validation, do đã làm "xong" và đưa lên forked repo nên em sẽ gửi nốt phần này và bắt đầu chuyển qua đưa code trực tiếp vào một nhánh khác trong repo chính

2024-11-07 13:48 UTC, suyttthideptrai commented on src/main/java/com/example/SS2_Backend/Ss2BackendApplication.java
> -
Không sửa gì thì không động vào

2024-11-07 13:49 UTC, suyttthideptrai commented on src/main/java/com/example/SS2_Backend/controller/GlobalExceptionHandler.java
> +
Không sửa gì thì không động vào

2024-11-09 14:57 UTC, han8129 requested changes

2024-11-09 14:57 UTC, han8129 commented on src/main/java/com/example/SS2_Backend/dto/request/NewStableMatchingProblemDTO.java
>      private List<List<Double>> individualProperties;
Thiếu việc kiểm tra dimension của các ma trận, 3 ma trận - requirement, weight, property phải có dimension tương tự nhau. số row của 3 ma trận phải bằng số individual. tương tự với 2 array setIndicies và capacities

2024-11-10 04:03 UTC, suyttthideptrai commented on src/main/java/com/example/SS2_Backend/controller/HomeController.java
> +    private ErrorMapper errorMapper;
Cái errorMapper này dùng trong trường hợp gì?

2024-11-10 04:04 UTC, suyttthideptrai commented on src/main/java/com/example/SS2_Backend/dto/request/NewStableMatchingProblemDTO.java
> +    public boolean isEvaluateFunctionValid() {
với hàm validate riêng biệt, e dùng kiểu trả về là void và truyền vào bindingResult nhé. Check valid bên trong hàm, nếu không valid thì bindingResult.reject("fieldName", message). Cuối cùng sau tất cả các bước validate thì mình check bindingResult.hasErrors(), nếu có thì mình trả về tất cả các lỗi

2024-11-12 17:09 UTC, han8129 requested changes

2024-11-14 08:16 UTC, suyttthideptrai approved these changes
hmm

2024-11-14 08:16 UTC, merged